export enum UserVisitTypeEnum {
  SIGN_IN_EMAIL = 'SIGN_IN_EMAIL',
  SIGN_IN_OAUTH = 'SIGN_IN_OAUTH',
  SIGN_IN_OAUTH_GOOGLE = 'SIGN_IN_OAUTH_GOOGLE',
  SIGN_OUT_EMAIL = 'SIGN_OUT_EMAIL',
  SIGN_OUT_OAUTH = 'SIGN_OUT_OAUTH',
  SIGN_OUT_OAUTH_GOOGLE = 'SIGN_OUT_OAUTH_GOOGLE',
}
